import { spawn } from 'node:child_process';
import { chromium } from 'playwright-core';
const ROOT = '/Users/wbtrex/website/localServer/node/trexwb/git/lockPass';
const BASE = 'http://localhost:1420';
const CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const server = spawn('node', ['scripts/serve.mjs'], { cwd: ROOT, stdio: 'ignore' });
await new Promise(r => setTimeout(r, 900));
const browser = await chromium.launch({ executablePath: CHROME, headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 }, serviceWorkers: 'block' });
const page = await ctx.newPage();
page.on('pageerror', e => console.log('PAGEERROR:', e.message));
await page.goto(BASE, { waitUntil: 'networkidle' });
await page.evaluate(async () => { const dbs = await indexedDB.databases(); for (const db of dbs) await new Promise(res => { const r = indexedDB.deleteDatabase(db.name); r.onsuccess = r.onerror = r.onblocked = res; }); });
await page.reload({ waitUntil: 'networkidle' });
await page.waitForSelector('#lock-screen');
await page.fill('#master-password', 'Test-Password-2026!');
await page.waitForTimeout(400); // 模拟 250ms 定时器窗口
await page.fill('#confirm-password', 'Test-Password-2026!');
const before = await page.evaluate(() => ({ m: document.getElementById('master-password').value, c: document.getElementById('confirm-password').value }));
console.log('before click:', JSON.stringify(before));
await page.click('#unlock-btn');
await page.waitForTimeout(3000);
const after = await page.evaluate(() => ({ m: document.getElementById('master-password').value, c: document.getElementById('confirm-password').value, err: document.getElementById('lock-error').textContent, errHidden: document.getElementById('lock-error').classList.contains('hidden') }));
console.log('after click:', JSON.stringify(after));
await browser.close(); server.kill(); process.exit(0);
